# Instances of grafana will only update datasource configurations
# for apiVersion numbers of same or lower. Thus, a new lower number
# will not affect higher number configuration settings.
# Typically BLUKWA keep this set to 1
apiVersion: 1

datasources:
  - name: 'Frequent Crawler 05 Embedded Prometheus'
    type: prometheus
    access: proxy
    orgId: 1
    url: http://192.168.45.15:9191
    isDefault: false
